## Load, Format and Inspect Data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('german2.csv')
data_numeric = pd.read_csv('germancredit.csv', header= None)

In [3]:
# columns = data.iloc[0].tolist()

In [4]:
# data.columns = columns

In [5]:
# data = data.iloc[1:]


In [6]:
data

account_status  duration  credit_history  purpose  credit_amount  \
0                11         6              34       43           1169   
1                12        48              32       43           5951   
2                14        12              34       46           2096   
3                11        42              32       42           7882   
4                11        24              33       40           4870   
..              ...       ...             ...      ...            ...   
995              14        12              32       42           1736   
996              11        30              32       41           3857   
997              14        12              32       43            804   
998              11        45              32       43           1845   
999              12        45              34       41           4576   

     savings_account  unemployed  installment_rate  personal_status_sex  \
0                 65          75                 4                   93   
1                 61          73                 2                   92   
2                 61          74                 2                   93   
3                 61          74                 2                   93   
4                 61          73                 3                   93   
..               ...         ...               ...                  ...   
995               61          74                 3                   92   
996               61          73                 4                   91   
997               61          75                 4                   93   
998               61          73                 4                   93   
999               62          71                 3                   93   

     debtors/guarantors  ...  property  age  other_installment_plans  housing  \
0                   101  ...       121   67                      143      152   
1                   101  ...       121   22                      143      152   
2                   101  ...       121   49                      143      152   
3                   103  ...       122   45                      143      153   
4                   101  ...       124   53                      143      153   
..                  ...  ...       ...  ...                      ...      ...   
995                 101  ...       121   31                      143      152   
996                 101  ...       122   40                      143      152   
997                 101  ...       123   38                      143      152   
998                 101  ...       124   23                      143      153   
999                 101  ...       123   27                      143      152   

     credits  job  liable_for  telephone  foreign_worker  good/bad  
0          2  173           1        192             201         1  
1          1  173           1        191             201         2  
2          1  172           2        191             201         1  
3          1  173           2        191             201         1  
4          2  173           2        191             201         2  
..       ...  ...         ...        ...             ...       ...  
995        1  172           1        191             201         1  
996        1  174           1        192             201         1  
997        1  173           1        191             201         1  
998        1  173           1        192             201         2  
999        1  173           1        191             201         1  

[1000 rows x 21 columns]

In [7]:
# data.columns = ['account_status', 'duration', 'credit_history', 'purpose', 'credit_amount', 'savings_account', 'unemployed', 'installment_rate', 'personal_status_sex', 'debtors/guarantors', 'present_residence_since', 'property', 'age', 'other_installment_plans', 'housing', 'credits', 'job', 'liable_for', 'telephone', 'foreign_worker', 'good/bad']

In [8]:
# data

In [9]:
# test = data.iloc[:,1:]
# test

In [10]:
# data.columns.tolist()

In [11]:
# data

In [12]:
# a_columns = ['account_status', 'credit_history', 'purpose', 'savings_account', 'unemployed',
#      'personal_status_sex', 'debtors/guarantors', 'property', 'other_installment_plans', 'housing', 'job', 'telephone', 'foreign_worker']

In [13]:
# data[a_columns] = data[a_columns].replace({'A':''}, regex=True)
# data

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
account_status             1000 non-null int64
duration                   1000 non-null int64
credit_history             1000 non-null int64
purpose                    1000 non-null int64
credit_amount              1000 non-null int64
savings_account            1000 non-null int64
unemployed                 1000 non-null int64
installment_rate           1000 non-null int64
personal_status_sex        1000 non-null int64
debtors/guarantors         1000 non-null int64
present_residence_since    1000 non-null int64
property                   1000 non-null int64
age                        1000 non-null int64
other_installment_plans    1000 non-null int64
housing                    1000 non-null int64
credits                    1000 non-null int64
job                        1000 non-null int64
liable_for                 1000 non-null int64
telephone                  1000 non-null int64
f

In [15]:
# data.to_csv('german2.csv', index=False)

In [16]:
#data.dropna(axis=1, inplace=True)

## Define X and y

In [17]:
X = data.iloc[1:, :-1].values
y = data.iloc[1:, -1].values

[(1, 699), (2, 699)]


In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

## Feature Scaling

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [20]:
print(X_train)

[[-0.49596658  0.02485567  1.36885619 ... -0.4215127   1.21660694
  -0.20069324]
 [ 1.10523588 -0.22901113  1.36885619 ... -0.4215127  -0.82195816
  -0.20069324]
 [ 1.10523588  0.27872247 -0.47516051 ... -0.4215127  -0.82195816
  -0.20069324]
 ...
 [-0.49596658 -0.99061153 -0.47516051 ... -0.4215127  -0.82195816
  -0.20069324]
 [-0.49596658 -1.24447834 -0.47516051 ... -0.4215127   1.21660694
  -0.20069324]
 [ 0.30463465 -0.90598927 -0.47516051 ... -0.4215127   1.21660694
  -0.20069324]]


In [21]:
print(X_test)

[[ 1.10523588  0.27872247 -0.47516051 ... -0.4215127  -0.82195816
  -0.20069324]
 [ 1.10523588 -0.48287793 -0.47516051 ...  2.37240776 -0.82195816
  -0.20069324]
 [ 1.10523588  0.27872247 -0.47516051 ... -0.4215127   1.21660694
  -0.20069324]
 ...
 [ 1.10523588 -0.73674473 -0.47516051 ... -0.4215127   1.21660694
  -0.20069324]
 [ 1.10523588  0.53258928  0.44684784 ... -0.4215127  -0.82195816
  -0.20069324]
 [ 1.10523588  0.02485567  0.44684784 ...  2.37240776 -0.82195816
  -0.20069324]]


## Training the Random Forest Classification Model on the Training Set

In [22]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=1000, criterion ='entropy', random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=1000, random_state=0)

In [23]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 2]
 [1 1]
 [2 2]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 2]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 2]
 [1 1]
 [2 1]
 [1 2]
 [1 1]
 [1 2]
 [1 2]
 [1 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [1 1]
 [1 2]
 [1 1]
 [1 2]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 2]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 2]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 2]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [1 1]
 [1 2]
 [1 1]
 [2 1]
 [1 1]
 [2 1]
 [1 2]
 [1 1]
 [2 2]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [2 2]
 [1 2]
 [2 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 2]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 2]
 [1 1]
 [2 2]
 [1 1]
 [1 2]
 [1 2]
 [2 2]

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[155  10]
 [ 50  35]]


0.76

In [27]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=0)
X_resampled, y_resampled = ros.fit_resample(X, y)
from collections import Counter
print(sorted(Counter(y_resampled).items()))

[(1, 699), (2, 699)]


array([[ 12,  48,  32, ...,   1, 191, 201],
       [ 14,  12,  34, ...,   2, 191, 201],
       [ 11,  42,  32, ...,   2, 191, 201],
       ...,
       [ 12,  24,  32, ...,   1, 192, 201],
       [ 12,  12,  32, ...,   1, 191, 201],
       [ 12,  24,  32, ...,   1, 192, 201]], dtype=int64)